### ISSUE TITLE
Moon Phase API seems to be offline

### ISSUE THREAD

**Issue by mowies** [jessamynsmith/eggtimer-server#17]
I forked the project and set everything up but I found that the request for the moon phase going out to https://api.usno.navy.mil seems to always run into a timeout for me. This slows down the view generation of the calendar because the server waits for the API to respond until it generates the rest

**Comment by jessamynsmith** [comment]
That's mysterious. I see it on heroku and my localhost. Perhaps that API is limited by location?

**Comment by jessamynsmith** [comment]
As a workaround, you could disable the call in calendar.js to $.getJSON(aerisUrl...

**Comment by mowies** [comment]
Yup I just removed that functionality in my fork
