### ISSUE TITLE
Calendar view shows wrong dates

### ISSUE THREAD

**Issue by lizzard** [jessamynsmith/eggtimer-server#2]
When I enter yesterday's date (May 25) as the first day of my period, it shows on the calendar as Sunday the 24th. I tried changing the timestamp to different times to see if that made a difference, but it did not.  Entering the first day as May 26 changed it to show on Monday the 25th.

**Comment by jessamynsmith** [comment]
Ah, thank you for letting me know! This is very likely a timezone issue. What timezone are you in?

**Comment by lizzard** [comment]
PST.

**Comment by lizzard** [comment]
Oh. I mean PDT !

**Comment by jessamynsmith** [comment]
Alright, I will take a look as soon as I can. I'm on a time-limited contract at the moment, so it'll be a couple days. Thanks again for letting me know!

**Comment by jessamynsmith** [comment]
I've begun the process of handling timezones correctly. You should have gotten an email notifying you of upcoming changes, and giving you the option to update your timezone in the app. Could you please confirm that you received that email, and that you've made changes as appropriate? Thanks!

**Comment by lizzard** [comment]
Hi!  I did get your email.  I changed my time zone to the correct one for me. 
I just tried entering data for this week, and created an entry for 7/21 and 7/22, leaving the default timestamps alone. Both entries appeared a day before (on 7/20 and 7/21). I'll try changing the times from the default to see if that helps.

**Comment by lizzard** [comment]
14:00 also appears as 11am (I am in PST)

**Comment by lizzard** [comment]
It's rough being a Time Lord.

**Comment by jessamynsmith** [comment]
It is a multistage process to fix this. Now that I have correct timezones in the database, I have to convert the data to UTC and the view logic to work correctly with UTC times. I can more or less guarantee you are going to continue to see weird behaviour until I've completed the process. Sorry for the inconvenience!

**Comment by jessamynsmith** [comment]
I just pushed out some major changes in how date times are stored and displayed. I believe it is working now, for timezones other than Eastern. If you could check it when you get a chance, I would greatly appreciate it.

**Comment by lizzard** [comment]
Impressive! This seems to work fine now. I am signed up as Pacific time and it now puts the entry on the correct day without my changing the time!

**Comment by jessamynsmith** [comment]
Great! I shall consider this closed. Let me know if you have any further issues.
